server:
  port: 9900

spring:
  application:
    name: gateway-service #服务名
  profiles:
    active: dev #环境设置
  cloud:
    gateway:
      routes:
        # 透传服务
        - id: gateway-client
          uri: lb://gateway-client
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix=1
        - id: gateway-consumer
          uri: lb://gateway-consumer
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=1
        - id: auth #设置路由id(理论上是可以随便写的)
          uri: lb://uaa-server #设置路由的url lb://nacos服务注册名称
          predicates:
            - Path=/api-uaa/** #路径匹配规则
          filters:
            - StripPrefix=1
            - PreserveHostHeader
        - id: auth-login-token
          uri: lb://uaa-server
          predicates:
            - Path=/oauth/token
          filters:
            - PreserveHostHeader
        - id: user-center
          uri: lb://user-center
          predicates:
            - Path=/center/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader
        - id: file-center
          uri: lb://file-center
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader
