server:
  port: 8002

spring:
  application:
    name: gateway-service #服务名
  profiles:
    active: dev #环境设置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos服务注册

    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: auth #设置路由id(理论上是可以随便写的)
          uri: lb://gateway-client #设置路由的url lb://nacos服务注册名称
          predicates:
            - Path=/testGrateway/** #路径匹配规则
